"""empty message

Revision ID: bfcca7691201
Revises: d35d259549ed
Create Date: 2019-06-25 12:26:17.146301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcca7691201'
down_revision = 'd35d259549ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('purpose', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_channel_purpose'), 'channel', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_purpose'), table_name='channel')
    op.drop_column('channel', 'purpose')
    # ### end Alembic commands ###
